### ISSUE TITLE
Livewire 3

### ISSUE THREAD

**Issue by ditsbroefs** [spatie/laravel-dashboard#112]
`spatie/laravel-dashboard 2.1.4 requires livewire/livewire ^2.0 -> found livewire/livewire[v2.0.0, ..., v2.12.6] but it conflicts with your root composer.json require `(^3.0)``

Making this package Livewire 3 compatible would make all Spatie fans very happy!

**Comment by freekmurze** [comment]
Yeah indeed, I'd accept a PR for that!

**Comment by ditsbroefs** [comment]
I was afraid you would say that ;). See Alexandru is working on it.
