### ISSUE TITLE
pgsql

### ISSUE THREAD

**Issue by thedangler** [spatie/laravel-dashboard#19]
Can I use postgres DB with this?

**Comment by freekmurze** [comment]
You can use any db that laravel supports.

**Comment by robclancy** [comment]
@freekmurze I came here for the same reason I assume OP asked this question. In your requirements page https://docs.spatie.be/laravel-dashboard/v1/requirements/ you say `MySQL 5.7 or higher is required.` which implies you have to use MySQL.

**Comment by freekmurze** [comment]
Ah yeah indeed. The most important bit db wise, is that the database should support json columns.
