### ISSUE TITLE
syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by DylanDec** [spatie/laravel-dashboard#34]
I made it locally, this worked perfectly. When I deployed my application with the dashboard to production I got this error.

`syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)`

**Comment by freekmurze** [comment]
You are not running the required PHP version.

**Comment by DylanDec** [comment]
I am running php version 7.4.6. The docs say you need 7.4+.

**Comment by freekmurze** [comment]
Please use these steps: https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running

**Comment by DylanDec** [comment]
![image](https://user-images.githubusercontent.com/14364739/83441815-71606f00-a447-11ea-8fff-2092fec7adca.png)

**Comment by freekmurze** [comment]
Our test prove that the package doesn’t have a syntax issue. 

If you think the package is in error, please PR a failing test.

**Comment by sebastiandedeyne** [comment]
I assume your webserver is using a different (older) PHP version that the version used by your CLI.

**Comment by dimitrijrt** [comment]
I got the same issue , how did you solve it please ?

**Comment by fadhelali1996** [comment]
open your projet in cmd and then insert this command echo 7.4>php-version , that because you use a php version 7.4.6 and your server run anather version

**Comment by Ahaim99** [comment]
> You are not running the required PHP version.

Update PHP Version to resolve this issue

**Comment by UsmanKhan172014** [comment]
Hey I am working on a legacy project and I need help. It only works on php 7.1 but according to above thread I need to use 7.4 can anybody help me with this?
my stack is
Zend framework 3.0
Node 8
php 7.1
And metronic theme 4.6
