### ISSUE TITLE
Dashboard positioning not rendered properly in a Bootstrap based template 

### ISSUE THREAD

**Issue by ssmusoke** [spatie/laravel-dashboard#40]
I am not sure where to start looking hence posting here, I have copied the sample Laravel charts dashboard tile as a test, the example below 

`<x-dashboard>
    <livewire:chart-tile chartFactory="{{\Fidum\ChartTile\Examples\ExamplePieChart::class}}" position="a1:a2" height="140%"/>
    <livewire:chart-tile chartFactory="{{\Fidum\ChartTile\Examples\ExampleDoughnutChart::class}}" position="b1:b2" height="140%"/>
    <livewire:chart-tile chartFactory="{{\Fidum\ChartTile\Examples\ExamplePieChart::class}}" position="c1:c2" height="140%" />
    <livewire:chart-tile chartFactory="{{\Fidum\ChartTile\Examples\ExampleDoughnutChart::class}}" position="d1:d2" height="140%" />
    <livewire:chart-tile chartFactory="{{\Fidum\ChartTile\Examples\ExampleBarChart::class}}" position="a3:b4" />
    <livewire:chart-tile chartFactory="{{\Fidum\ChartTile\Examples\ExampleLineChart::class}}" position="c3:d4" />
    <livewire:chart-tile chartFactory="{{\Fidum\ChartTile\Examples\ExampleLineChart::class}}" position="a5:b6" />
    <livewire:chart-tile chartFactory="{{\Fidum\ChartTile\Examples\ExampleBarChart::class}}" position="c5:d6" />
    <livewire:chart-tile chartFactory="{{\Fidum\ChartTile\Examples\ExampleBarChart::class}}" position="a7:b8" />
    <livewire:chart-tile chartFactory="{{\Fidum\ChartTile\Examples\ExampleLineChart::class}}" position="c7:d8" />
</x-dashboard>`

renders as the image below 

<img width="1854" alt="Screenshot 2020-07-03 16 53 12" src="https://user-images.githubusercontent.com/689900/86475815-04920a80-bd4e-11ea-800c-2e5f0df7ec61.png">

I see in the generated HTML 

`<canvas id="chart_Pcvl8uG4f9oKFP5iVlfS" height="1672" style="display: block; height: 1254px; width: 2688px;" width="3584" class="chartjs-render-monitor"></canvas>` which I suspect is the problem or is it

The full HTML for the first element is 

`<div class="absolute inset-0 overflow-hidden p-4" style="mask-image: linear-gradient(black, black calc(100% - 1rem), transparent);"><div class="grid grid-rows-auto-1 gap-3 h-full"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div><canvas id="chart_Pcvl8uG4f9oKFP5iVlfS" height="1672" style="display: block; height: 1254px; width: 2688px;" width="3584" class="chartjs-render-monitor"></canvas> <div id="chart_Pcvl8uG4f9oKFP5iVlfS_loader" style="display: none; justify-content: center; opacity: 1; align-items: center;"><svg width="50" height="50" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient x1="8.042%" y1="0%" x2="65.682%" y2="23.865%" id="a"><stop stop-color="#22292F" stop-opacity="0" offset="0%"></stop> <stop stop-color="#22292F" stop-opacity=".631" offset="63.146%"></stop> <stop stop-color="#22292F" offset="100%"></stop></linearGradient></defs> <g fill="none" fill-rule="evenodd"><g transform="translate(1 1)"><path d="M36 18c0-9.94-8.06-18-18-18" id="Oval-2" stroke="url(#a)" stroke-width="2"><animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="0.9s" repeatCount="indefinite"></animateTransform></path> <circle fill="#22292F" cx="36" cy="18" r="1"><animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="0.9s" repeatCount="indefinite"></animateTransform></circle></g></g></svg></div></div> <div wire:id="alPldAc999aJKBEISJS7" wire:poll.3600s="" class="hidden"></div></div>`

I suspect that it is the template styling but I have no idea what element styling would cause this

**Comment by ssmusoke** [comment]
Closing issue, must be something local

**Comment by jamesRUS52** [comment]
> Closing issue, must be something local

How did you solve the problem?
I want disable tailwind css, but \Fidum\ChartTile not working properly after this 
Where Can I find inline for bootstrap?
