### ISSUE TITLE
Found incorrect reference in documentation

### ISSUE THREAD

**Issue by robwilde** [spatie/laravel-dashboard#5]
Discovered the information to publish the provider view for time-weather dashboard is referencing Calendar.
file:
`docs/adding-tiles/time-weather.md`

`php artisan vendor:publish --provider="Spatie\CalendarTile\CalendarTileServiceProvider" --tag="dashboard-calendar-tile-views"`

and should be:
`php  artisan vendor:publish --provider="Spatie\TimeWeatherTile\TimeWeatherTileServiceProvider" --tag="dashboard-time-weather-tile-views"`

I attempted to make a pull request but submission is restricted

**Comment by freekmurze** [comment]
There's an edit button on every page that allows you to create a PR.

I'll fix this one myself. Thanks!
