### ISSUE TITLE
Changelog link mismatch

### ISSUE THREAD

**Issue by tvbeek** [spatie/laravel-dashboard#54]
The changelog on the docs site (url: https://spatie.be/docs/laravel-dashboard/v2/changelog ) points to: https://github.com/spatie/laravel-dashboard/blob/master/docs/changelog.md that is a file without the information about the changes.   
The changelog in https://github.com/spatie/laravel-dashboard/blob/master/CHANGELOG.md has the changes.

Is it wanted to have the documentation linked to the changelog in the root of the project or is it wanted to have it in the docs directory?

I'm willing to create a PR but not sure how it is wanted.

**Comment by freekmurze** [comment]
Feel free to PR that change.
