### ISSUE TITLE
Laravel 8 Install fail

### ISSUE THREAD

**Issue by myscienceisbetter** [spatie/laravel-dashboard#59]
When I try to install in Laravel 8 I get this error:

`composer require spatie/laravel-dashboard
Using version ^2.0 for spatie/laravel-dashboard
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError

  Argument 1 passed to Spatie\Dashboard\Dashboard::script() must be of the type string, null given, called in /<full_path>/vendor/spatie/laravel-dashboard/src/DashboardServiceProvider.php on line 18

  at vendor/spatie/laravel-dashboard/src/Dashboard.php:20
     16▕     public array $stylesheets = [];
     17▕
     18▕     public array $inlineStylesheets = [];
     19▕
  ➜  20▕     public function script(string $url): self
     21▕     {
     22▕         $this->scripts[] = $url;
     23▕
     24▕         return $this;

      +9 vendor frames
  10  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Spatie\Dashboard\DashboardServiceProvider))

      +5 vendor frames
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.`

**Comment by fscaptain** [comment]
Hi,
actially do teh same, fresh install of Laravel8, Jetstream with Livewire ans Spatie Laravel Dashboard.
I got no Errors, all runs as described in the documentaion?

**Comment by freekmurze** [comment]
Cannot reproduce this.

**Comment by benjaminbowles** [comment]
I get this exact error installing on a recently upgraded Laravel 8 project.

**Comment by makhweb** [comment]
The same error
