### ISSUE TITLE
Multiple dashboards for different users

### ISSUE THREAD

**Issue by davenorthcreek** [spatie/laravel-dashboard#63]
I'm building an internal dashboard, and each user is going to be interested in a different set of tiles.  Can I load a different dashboard per user?  I can load a blade template based on id - either constructed from the database or generated on a database change and stored somewhere in the `resources/views` file hierarchy.  But I can't get livewire to render the result, so all I serve is the bare `<x-dashboard>...</x-dashboard>` html.

Is there a way to force livewire to render a template after choosing the right template dynamically?

**Comment by freekmurze** [comment]
I think you could solve this by just rendering the components you'd like in Blade.

```
<x-dashboard>
@foreach($user->components as $component)
    {{ $component->toHtml() }}
@foreach
</x-dashboard>
```

`Component` should be a model of your own that knows how to render itself to the right html.

**Comment by davenorthcreek** [comment]
![image](https://user-images.githubusercontent.com/8632950/95227134-faebc900-07ba-11eb-8c24-90348c0e8711.png)
This is a screenshot (I've put the dashboard in an iframe so that's why there's a heading there.  The php code isn't being rendered because it's inside the dashboard $slot.  I think I need to change the order of operations.

**Comment by davenorthcreek** [comment]
Generating the proper blade template is pretty simple.  It's getting the generated blade template to render when we are choosing it dynamically that I can't figure out.  I think it comes from the laravel pipeline - when things are rendered.  I think I need to find a way to delay the livewire rendering until I've set up the dynamic blade templates.  I think this is requires some changes that could end up opening up the dashboard to a whole new set of use cases.

**Comment by davenorthcreek** [comment]
Given this code instead:
`<x-dashboard>
    <?php
        foreach(Auth::user()->dashboard->assignments as $component) {
            print $component->toHtml().PHP_EOL;
        }
    ?>
</x-dashboard>
`
I was able to generate the following (this is view page source):
`<x-dashboard>
    <livewire:dummy position="A1:A2" />
<livewire:dummy position="A3:A4" />
<livewire:dummy position="B1:B2" />
<livewire:dummy position="B3:B4" />
<livewire:dummy position="C1:C1" />
</x-dashboard>
`
But the template is generated too late in the pipeline for this dashboard to be rendered, so this non-standard html is just left as is and sent to the browser.

**Comment by davenorthcreek** [comment]
Here's my working laravel/adminlte/spatie-dashboard/livewire dashboard with admin capabilities.
Members by invite only.
Editable dashboards per member.
No real documentation but it might be useful for your next iteration of the dashboard.

https://github.com/davenorthcreek/devops

Feel free to do what you like with it.  I'll send you a postcard next time I'm near a post office.

Cheers from Onoway, Alberta.
