### ISSUE TITLE
Weather Tile not rendering anything

### ISSUE THREAD

**Issue by 8humayun8** [spatie/laravel-dashboard#9]
`<x-dashboard>
    <livewire:time-weather-tile position="a1" />
</x-dashboard>`

is not rendering anything.. i have followed the doc. there is a data in my database of weather component but no on dashboard.

Please help!

**Comment by freekmurze** [comment]
Are you getting an exception in the log or in the console?

Without some more context, it's hard to help you.

**Comment by 8humayun8** [comment]
Gotcha.. 
With this `Route::view('dashboard-url', 'dashboard-blade-view');` got nothing..
But with this 

```
Route::get('/', function () {
    return view('welcome');
});
```

its working ..

**Comment by freekmurze** [comment]
What is the HTML output of your route?
Are you getting an error either in the console of your browser or in the application log?

**Comment by 8humayun8** [comment]
i am totally insane. :( i was naming blade file like this `dashboard-blade-view.php` just copying and pasting.  it working now. 
Thanks for your time.
